import ts from "typescript";
import TsConfig from "../utils/tsconfig.js";
import type { Point } from "./suseeConfig.js";

class CompilerOptions {
	private _point: Point;
	private _options: ts.CompilerOptions;
	constructor(point: Point) {
		this._point = point;
		this._options = {};
	}
	private __init() {
		const __opts = new TsConfig(this._point.tsconfigFilePath);
		__opts.removeCompilerOption("rootDir");
		__opts.removeCompilerOption("module");
		__opts.editCompilerOptions({
			moduleResolution: ts.ModuleResolutionKind.NodeNext,
			outDir: this._point.outDirPath,
			allowJs: true,
		});
		this._options = __opts.getCompilerOptions();
	}
	private __init2() {
		this.__init();
		let { types, lib, ...restOptions } = this._options;
		// normalize types into an array
		if (types) {
			if (!types.includes("node")) {
				types = ["node", ...types];
			}
		} else {
			types = ["node"];
		}
		if (lib) {
			lib = [...new Set(["ESNext", ...lib])];
		} else {
			lib = ["ESNext"];
		}
		return { types, lib, ...restOptions } as ts.CompilerOptions;
	}
	/**
	 * Gets the compiler options for CommonJS.
	 * @returns The compiler options for CommonJS.
	 */
	public get commonjs() {
		const opts = this.__init2();
		const { module, ...rest } = opts;
		return { module: ts.ModuleKind.CommonJS, ...rest } as ts.CompilerOptions;
	}
	/**
	 * Gets the compiler options for ESM.
	 * @returns The compiler options for ESM.
	 * @remarks The compiler options are generated by calling {@link __init2} and then setting the module type to {@link ts.ModuleKind.ES2020}.
	 */
	public get esm() {
		const opts = this.__init2();
		const { module, ...rest } = opts;
		return { module: ts.ModuleKind.ES2020, ...rest } as ts.CompilerOptions;
	}
	/**
	 * Returns the default compiler options.
	 * @returns The default compiler options.
	 * @remarks The default compiler options are generated by calling {@link __init2}.
	 */
	public get default() {
		return this.__init2();
	}
	public get browser() {
		const opts = this.__init2();
		const { module, declaration, declarationMap, outDir, ...rest } = opts;
		const exportPaths = this._point.outDirPath.split("/");
		const out_dir =
			this._point.exportPath === "."
				? `${this._point.outDirPath}/browser`
				: `${exportPaths[0]}/browser/${exportPaths.slice(1).join("/")}`;
		return {
			module: ts.ModuleKind.ES2020,
			declaration: false,
			declarationMap: false,
			outDir: out_dir,
			...rest,
		} as ts.CompilerOptions;
	}
}

/**
 * Returns an instance of CompilerOptions, which provides various methods
 * to generate different sets of compiler options based on the
 * given Point.
 *
 * @param {Point} point - The point to generate compiler options for.
 * @returns {CompilerOptions}
 */
function compilerOptions(point: Point): CompilerOptions {
	return new CompilerOptions(point);
}

export { compilerOptions };
